version: '3.8'

services:
  nginx:
    image: octoross/inception-nginx
    container_name: nginx_inception
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
      # - "80:80"
    # na pas besoin dexpose, il est serveur pas client, il envoie sur un port (9000 pour wordpress) et na rien a ecouter 
    volumes:
      - wordpress-website:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - frontend
    restart: always

  wordpress:
    image: octoross/inception-wordpress
    container_name: wordpress_inception
    build: ./requirements/wordpress
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - wordpress-website:/var/www/html
      - state:/app/state/
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - WEBSITE_TITLE=${WEBSITE_TITLE}
      - WP_ADMIN_NAME=${WP_ADMIN_NAME}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER_NAME=${WP_USER_NAME}
      - WP_USER_PASS=${WP_USER_PASS}
      - WP_USER_MAIL=${WP_USER_MAIL}

  mariadb:
    image: octoross/inception-mariadb
    container_name: mariadb_inception
    build: ./requirements/mariadb
    env_file:
      .env
    expose:
      - 3306
    volumes:
      - database:/var/lib/mysql
      - state:/app/state/
    networks:
      - backend
    restart: always


volumes:
  wordpress-website:
  database:
  state:

networks:
  frontend:
  backend:
