version: '3.8'

services:
  nginx:
    image: octoross/inception-nginx
    container_name: nginx_inception
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
      - "80:80"
    # na pas besoin dexpose, il est serveur pas client, il envoie sur un port (9000 pour wordpress) et na rien a ecouter 
    volumes:
      - certificates:/etc/ssl/certs:rw
      - wordpress-website:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - frontend
    restart: always

  wordpress:
    image: octoross/inception-wordpress
    container_name: wordpress_inception
    build: ./requirements/wordpress
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - wordpress-website:/var/www/html
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: always

  mariadb:
    image: octoross/inception-mariadb
    container_name: mariadb_inception
    build: ./requirements/mariadb
    env_file:
      .env
    expose:
      - "$DB_PORT"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend
    restart: always


volumes:
  certificates:
  wordpress-website:
  mariadb:

networks:
  frontend:
  backend:
